### PR TITLE
nvd3 graph iteration

### PR DESCRIPTION
**Pull request by rubinovitz**
screen shot 2017-10-22 at 9 47 42 pm

^ screenshot

Current apparent issues to me:
-  Mining amount does not change much so graph is boring
-  Need to decide what intervals to show on the x axis and then I can adjust margins
-  Naming things e.g. margins
- Colors whenever we decide on colors

### CODE REVIEW

**Comment by frnsys** [comment]
@rubinovitz this may be a weird question, but is the code in this PR the same code that generated the screenshot? I'm having trouble with getting it working -- it seems to be using a different data source?

**Comment by rubinovitz** [comment]
Interesting, I shall double check now

**Comment by rubinovitz** [comment]
(it was working for me in that screenshot, but i did have to move my work over to this repo late yesterday so wondering if i missed something)

**Comment by rubinovitz** [comment]
I'm now getting different data from the API than I did previously.

**Comment by frnsys** [comment]
I had to update the wallet address and reset the db, so there's not as much data now -- but I don't see where in the PR the API is being called?

**Comment by rubinovitz** [comment]
just pushed the js file up, sorry, changing repos in the middle of working on this was a pain.

**Pull request merged**
