### PR TITLE
Add linux to electron builds and include 7zip to dev dependencies

### PR DESCRIPTION
**Pull request by joncinque**

### CODE REVIEW

**Comment by rubinovitz** [comment]
Thanks, Jon!

**Comment by joncinque** [comment]
You're very welcome!

**Comment by crashspringfield** [comment]
So this is causing install issues on Windows. `npm install` gives the following error:

    npm ERR! code EBADPLATFORM
    npm ERR! notsup Unsupported platform for 7zip-bin-linux@1.2.0: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
    npm ERR! notsup Valid OS:    linux
    npm ERR! notsup Valid Arch:  any
    npm ERR! notsup Actual OS:   win32
    npm ERR! notsup Actual Arch: x64

I'm not sure if there is a way to make dependencies conditional on the OS. I guess the other solution would just be adding a note to the README.md about removing it?

**Comment by joncinque** [comment]
I don't have a Windows machine ready to use, so you would need to try this on your side.  Can you change the devDependencies in desktop/package.json from:
```
  "devDependencies": {
    "electron": "^1.6.11",
    "electron-builder": "^19.22.1",
    "node-icns": "0.0.4",
    "7zip-bin-linux": "^1.2.0"
  },
```
to
```
  "devDependencies": {
    "electron": "^1.6.11",
    "electron-builder": "^19.22.1",
    "node-icns": "0.0.4",
    "7zip-bin": "^2.3.4"
  },
```
That *should* be platform agnostic.  This package seems to cause issues with npm, so if that still doesn't work, the line can be removed.  Let me know how it works out.

**Comment by rubinovitz** [comment]
@joncinque cool I will test it on Windows shortly.

**Comment by rubinovitz** [comment]
@joncinque  it's working on windows for me

**Comment by joncinque** [comment]
The packaged installer is working, but unfortunately 7zip-bin installs different packages to package-lock.json depending on your architecture.  That means package-lock would get modified anytime someone with a different architecture made changes.  To get rid of this issue, I'll remove 7zip-bin entirely and add a line in the README in desktop specifying that this optional dependency may need to be installed.

**Pull request merged**
